# Generated by Django 3.0.1 on 2020-01-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTypes',
            fields=[
                ('id', models.IntegerField(auto_created=True, verbose_name='序号')),
                ('book_type_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='类型编号')),
                ('book_type_name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('book_type_super', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='son', to='books.BookTypes', verbose_name='父类型编号')),
            ],
            options={
                'verbose_name': '商品类型信息表',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(auto_created=True, verbose_name='序号')),
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='图书编号')),
                ('book_name', models.CharField(max_length=100, verbose_name='图书名称')),
                ('book_author', models.CharField(max_length=100, verbose_name='图书作者')),
                ('book_price', models.FloatField(max_length=7, verbose_name='图书价格')),
                ('book_inventory', models.IntegerField(verbose_name='图书库存')),
                ('book_publisher', models.CharField(max_length=100, verbose_name='图书出版社')),
                ('book_publish_time', models.DateTimeField(verbose_name='图书出版时间')),
                ('book_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_type', to='books.BookTypes')),
            ],
            options={
                'verbose_name': '商品信息表',
            },
        ),
    ]
