# Generated by Django 3.0.1 on 2020-01-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_type_id',
            new_name='book_type',
        ),
    ]
