# Generated by Django 3.0.1 on 2020-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200116_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图书图片地址'),
        ),
    ]
