# Generated by Django 3.0.1 on 2020-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200117_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图书作者'),
        ),
    ]
