# Generated by Django 3.0.1 on 2020-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200117_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图书作者'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=200, verbose_name='图书名称'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_publisher',
            field=models.CharField(max_length=200, verbose_name='图书出版社'),
        ),
    ]
