# Generated by Django 3.0.1 on 2020-01-15 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.IntegerField(auto_created=True, verbose_name='序号')),
                ('log_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='日志编号')),
                ('name', models.CharField(max_length=100, verbose_name='客户/员工名称')),
                ('somethings', models.CharField(max_length=100, verbose_name='执行事件')),
                ('runtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '日志信息表',
            },
        ),
    ]
