# Generated by Django 3.0.1 on 2020-01-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客户/员工名称'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='somethings',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='执行事件'),
        ),
    ]
